import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import '../../build.css';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Landing Page',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<head>
				<link
					href='https://api.fontshare.com/v2/css?f[]=clash-display@300,400,500,600,700&display=swap'
					rel='stylesheet'
				/>
			</head>
			<body className={'w-full'}>{children}</body>
		</html>
	);
}
// inter.classname
